version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://localhost:27017/DCI-Place

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
