services:
  backend:
    build: ./backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://localhost:27017/DCI-Place
      - JWT_SECRET=530cc3647a17c3c5ffaaf0a7a479f3cb2d368f3d731714591e6cfcce7f46a290
      - SESSION_SECRET=test
      # Nodemailer
      - EMAIL_HOST=sandbox.smtp.mailtrap.io # smtp Host
      - EMAIL_PORT=465 # 465 SSL, 587 TLS
      - EMAIL_USER=7b4b41383d1fb0 # Google Email
      - EMAIL_PASS=52a0eee6e201c6 # Google App Password
      # Google Auth
      - GOOGLE_CLIENT_ID=test
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_CALLBACK_URL=http://localhost:5000/api/auth/google/callback
      # Node-Umgebung
      - NODE_ENV=development
    ports:
      - 5000:5000

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
